openapi: "3.0.0"
info:
  title: PRODUCT API DOC
  version: "0.0.1"
  description: PRODUCT API DOC
tags:
  - name: opts
    description: 運用監視関連のAPI
  - name: users
    description: ユーザー管理
  - name: meeting
    description: ミーティング
servers:
  - url: http://localhost:8085/api
paths:

  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /user/role:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
        '403':
          description: 認証エラー


  /user/signup:
    post:
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserForm"
      responses:
        '201':
          description: SIGNUP SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
        '404':
          description: UserNotFoundError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
    put:
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserForm"
      responses:
        '200':
          description: SIGNUP SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
        '404':
          description: UserNotFoundError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
  /user/login:
    post:
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserForm"
      responses:
        '200':
          description: LOGIN SUCCESS
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
          headers:
            Set-Cookie:
              schema:
                type: string
                example: JSESSIONID=abcde12345; Path=/; HttpOnly
        '404':
          description: UserNotFoundError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
        '403':
          description: ForbiddenError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
  /user/manage:
    post:
      responses:
        '200':
          description: OK
        '401':
          description: NG
  /meeting:
    get:
      tags:
        - meeting
      responses:
        '200':
          description: 会議一覧
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeetingResponseDTOList"


components:
  schemas:
    LoginUserForm:
      description: ログイン時のユーザー情報
      properties:
        email:
          type: string
          description: "ログインEmail"
        password:
          type: string
          description: "パスワード"
      required:
        - email
        - password
    UserResponseDTO:
      description: ログイン時の結果情報
      properties:
        role:
          type: string
          description: "ROLE"
        email:
          type: string
          description: "email"
      required:
        - role
        - email
    MeetingResponseDTO:
      description: メーティングの結果情報
      properties:
        id:
          type: integer
          format: int64
          description: "ID"
        title:
          type: string
          description: "title"
      required:
        - id
        - title
    MeetingResponseDTOList:
      type: object
      description: ミーティングのリスト
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/MeetingResponseDTO"
      required:
        - results
    ForbiddenError:
      description: アクセス権限がありません
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイプ"
          default: "パスワードが違います"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    ResourceNotFoundError:
      description: 指定したリソースは存在しない
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイプ"
          default: "Resource Not Found"
        detail:
          type: string
          description: "エラーの詳細"
      required:
        - title
        - detail
    UserNotFoundError:
      description: "対象のユーザが見つからない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイプ"
          default: "User Not Found"
        detail:
          type: string
          description: "エラーの詳細"
          default: "ユーザが見つかりません"
      required:
        - title
        - detail
    MeetingNotFoundError:
      description: "対象のMeetingが見つからない"
      type: object
      properties:
        title:
          type: string
          description: "エラーのタイプ"
          default: "Meeting Not Found"
        detail:
          type: string
          description: "エラーの詳細"
          default: "ユーザが見つかりません"
      required:
        - title
        - detail
    BadRequestError:
      description: 不正リクエスト
      type: object
      properties:
        title:
          type: string
          description: エラータイトル
          default: "BadRequest"
        detail:
          type: string
          description: ""
          default: "リクエストが不正です。再度リクエストを送信してください"
        invalid-params:
          type: array
          items:
            $ref: "#/components/schemas/InvalidParam"
    InvalidParam:
      description: "不正リクエストについての詳細"
      type: object
      properties:
        name:
          type: string
          description: エラーが発生したフィールド名
        reason:
          type: string
          description: エラーの理由
      required:
        - name
        - reason












